=== aws/porting-assistant-dotnet-client/tests/PortingAssistant.Client.IntegrationTests/TestProjects/Schemas/api-analysis-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "JSON Schema for Porting Assistant package analysis json output",
  "additionalProperties": false,

  "type": "object",
  "properties": {
    "SchemaVersion": {
      "type": "string"
    },
    "SolutionFile": {
      "type": "string"
    },
    "ApplicationGuid": {
      "type": "string"
    },
    "SolutionGuid": {
      "type": [
        "null",
        "string"
      ]
    },
    "RepositoryUrl": {
      "type": [
        "null",
        "string"
      ]
    },
    "ProjectGuid": {
      "type": [
        "null",
        "string"
      ]
    },
    "ProjectFile": {
      "type": "string"
    },
    "Errors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "SourceFileAnalysisResults": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "SourceFileName": {
            "type": "string"
          },
          "SourceFilePath": {
            "type": "string"
          },
          "ApiAnalysisResults": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "CodeEntityDetails": {
                  "$ref": "#/$defs/CodeEntityDetails"
                },
                "CompatibilityResults": {
                  "$ref": "#/$defs/CompatibilityResults"
                },
                "Recommendations": {
                  "$ref": "#/$defs/Recommendations"
                }
              }
            }
          },
          "RecommendedActions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "RecommendedActionType": {
                  "enum": [
                    "NoRecommendation",
                    "ReplaceApi",
                    "ReplaceNamespace",
                    "ReplacePackage",
                    "UpgradePackage"
                  ],
                  "type": "string"
                },
                "Description": {
                  "type": [
                    "null",
                    "string"
                  ]
                },
                "TextSpan": {
                  "type": "object",
                  "properties": {
                    "StartCharPosition": {
                      "type": "number"
                    },
                    "EndCharPosition": {
                      "type": "number"
                    },
                    "StartLinePosition": {
                      "type": "number"
                    },
                    "EndLinePosition": {
                      "type": "number"
                    }
                  }
                },
                "TargetCPU": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "enum": [
                      "x86",
                      "x64",
                      "ARM32",
                      "ARM64"
                    ]
                  }
                },
                "TextChanges": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "NewText": {
                        "type": "string"
                      },
                      "FileLinePositionSpan": {
                        "type": "object",
                        "properties": {
                          "Path": {
                            "type": "string"
                          },
                          "HasMappedPath": {
                            "type": "boolean"
                          },
                          "StartLinePosition": {
                            "$ref": "#/$defs/LinePosition"
                          },
                          "EndLinePosition": {
                            "$ref": "#/$defs/LinePosition"
                          },
                          "Span": {
                            "type": "object",
                            "properties": {
                              "Start": {
                                "$ref": "#/$defs/LinePosition"
                              },
                              "End": {
                                "$ref": "#/$defs/LinePosition"
                              }
                            }
                          },
                          "IsValid": {
                            "type": "boolean"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "SolutionFile",
    "ProjectFile",
    "Errors"
  ],
  "$defs": {
    "CodeEntityDetails": {
      "type": "object",
      "properties": {
        "CodeEntityType": {
          "enum": [
            "Class",
            "ClassAttribute",
            "InstanceAttribute",
            "Method",
            "Namespace",
            "Annotation",
            "Declaration",
            "Using",
            "Enum",
            "Struct"
          ],
          "type": "string"
        },
        "Namespace": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "Signature": {
          "type": "string"
        },
        "OriginalDefinition": {
          "type": "string"
        },
        "TextSpan": {
          "type": "object",
          "properties": {
            "StartCharPosition": {
              "type": "number"
            },
            "EndCharPosition": {
              "type": "number"
            },
            "StartLinePosition": {
              "type": "number"
            },
            "EndLinePosition": {
              "type": "number"
            }
          }
        },
        "Package": {
          "type": "object",
          "properties": {
            "PackageId": {
              "type": "string"
            },
            "Version": {
              "type": "string"
            },
            "PackageSourceType": {
              "enum": [
                "SDK",
                "NUGET",
                "PORTABILITY_ANALYZER",
                "RECOMMENDATION",
                "PRIVATE"
              ]
            }
          }
        }
      }
    },
    "CompatibilityResults": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "Compatibility": {
            "enum": [
              "COMPATIBLE",
              "DEPRACATED",
              "INCOMPATIBLE",
              "UNKNOWN"
            ],
            "type": "string"
          },
          "CompatibleVersions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "Recommendations": {
      "type": "object",
      "properties": {
        "RecommendedActions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "RecommendedActionType": {
                "enum": [
                  "NoRecommendation",
                  "ReplaceApi",
                  "ReplaceNamespace",
                  "ReplacePackage",
                  "UpgradePackage"
                ],
                "type": "string"
              },
              "Description": {
                "type": [
                  "null",
                  "string"
                ]
              }
            }
          }
        }
      }
    },
    "LinePosition": {
      "type": "object",
      "properties": {
        "Line": {
          "type": "number"
        },
        "Character": {
          "type": "number"
        }
      }
    }
  }
}

=== aws/porting-assistant-dotnet-client/tests/PortingAssistant.Client.IntegrationTests/TestProjects/NetFrameworkExample-analyze/NetFrameworkExample-api-analysis.json
{
  "SolutionFile": "NetFrameworkExample",
  "ProjectFile": "NetFrameworkExample",
  "ProjectGuid": null,
  "Errors": [],
  "SourceFileAnalysisResults": [
    {
      "SourceFileName": "BundleConfig.cs",
      "SourceFilePath": "C:\\Users\\Administrator\\Documents\\workplace\\test-project\\NetFrameworkExample\\NetFrameworkExample\\NetFrameworkExample\\App_Start\\BundleConfig.cs",
      "ApiAnalysisResults": [
        {
          "CodeEntityDetails": {
            "CodeEntityType": "Namespace",
            "Name": "Add",
            "Namespace": "System.Web.Optimization",
            "Signature": "System.Web.Optimization.BundleCollection.Add(System.Web.Optimization.Bundle)",
            "OriginalDefinition": "System.Web.Optimization.BundleCollection.Add(System.Web.Optimization.Bundle)",
            "TextSpan": {
              "StartCharPosition": 13,
              "EndCharPosition": 58,
              "StartLinePosition": 11,
              "EndLinePosition": 12
            },
            "Package": {
              "PackageId": "System.Web.Optimization",
              "Version": "1.1.0",
              "PackageSourceType": "NUGET"
            }
          },
          "CompatibilityResults": {
            "netcoreapp3.1": {
              "Compatibility": "UNKNOWN",
              "CompatibleVersions": []
            }
          },
          "Recommendations": {
            "RecommendedActions": [
              {
                "CodeEntityDetails": null,
                "RecommendedActionType": "NoRecommendation",
                "Description": null,
                "TextSpan": null,
                "TargetCPU": null,
                "TextChanges": null
              }
            ]
          }
        },
        {
          "CodeEntityDetails": {
            "CodeEntityType": "Namespace",
            "Name": "Include",
            "Namespace": "System.Web.Optimization",
            "Signature": "System.Web.Optimization.Bundle.Include(string, params System.Web.Optimization.IItemTransform[])",
            "OriginalDefinition": "System.Web.Optimization.Bundle.Include(string, params System.Web.Optimization.IItemTransform[])",
            "TextSpan": {
              "StartCharPosition": 25,
              "EndCharPosition": 57,
              "StartLinePosition": 11,
              "EndLinePosition": 12
            },
            "Package": {
              "PackageId": "System.Web.Optimization",
              "Version": "1.1.0",
              "PackageSourceType": "NUGET"
            }
          },
          "CompatibilityResults": {
            "netcoreapp3.1": {
              "Compatibility": "UNKNOWN",
              "CompatibleVersions": []
            }
          },
          "Recommendations": {
            "RecommendedActions": [
              {
                "CodeEntityDetails": null,
                "RecommendedActionType": "NoRecommendation",
                "Description": null,
                "TextSpan": null,
                "TargetCPU": null,
                "TextChanges": null
              }
            ]
          }
        },
        {
          "CodeEntityDetails": {
            "CodeEntityType": "Namespace",
            "Name": "Add",
            "Namespace": "System.Web.Optimization",
            "Signature": "System.Web.Optimization.BundleCollection.Add(System.Web.Optimization.Bundle)",
            "OriginalDefinition": "System.Web.Optimization.BundleCollection.Add(System.Web.Optimization.Bundle)",
            "TextSpan": {
              "StartCharPosition": 13,
              "EndCharPosition": 55,
              "StartLinePosition": 14,
              "EndLinePosition": 15
            },
            "Package": {
              "PackageId": "System.Web.Optimization",
              "Version": "1.1.0",
              "PackageSourceType": "NUGET"
            }
          },
          "CompatibilityResults": {
            "netcoreapp3.1": {
              "Compatibility": "UNKNOWN",
              "CompatibleVersions": []
            }
          },
          "Recommendations": {
            "RecommendedActions": [
              {
                "CodeEntityDetails": null,
                "RecommendedActionType": "NoRecommendation",
                "Description": null,
                "TextSpan": null,
                "TargetCPU": null,
                "TextChanges": null
              }
            ]
          }
        },
        {
          "CodeEntityDetails": {
            "CodeEntityType": "Namespace",
            "Name": "Include",
            "Namespace": "System.Web.Optimization",
            "Signature": "System.Web.Optimization.Bundle.Include(string, params System.Web.Optimization.IItemTransform[])",
            "OriginalDefinition": "System.Web.Optimization.Bundle.Include(string, params System.Web.Optimization.IItemTransform[])",
            "TextSpan": {
              "StartCharPosition": 25,
              "EndCharPosition": 54,
              "StartLinePosition": 14,
              "EndLinePosition": 15
            },
            "Package": {
              "PackageId": "System.Web.Optimization",
              "Version": "1.1.0",
              "PackageSourceType": "NUGET"
            }
          },
          "CompatibilityResults": {
            "netcoreapp3.1": {
              "Compatibility": "UNKNOWN",
              "CompatibleVersions": []
            }
          },
          "Recommendations": {
            "RecommendedActions": [
              {
                "CodeEntityDetails": null,
                "RecommendedActionType": "NoRecommendation",
                "Description": null,
                "TextSpan": null,
                "TargetCPU": null,
                "TextChanges": null
              }
            ]
          }
        },
        {
          "CodeEntityDetails": {
            "CodeEntityType": "Namespace",
            "Name": "Add",
            "Namespace": "System.Web.Optimization",
            "Signature": "System.Web.Optimization.BundleCollection.Add(System.Web.Optimization.Bundle)",
            "OriginalDefinition": "System.Web.Optimization.BundleCollection.Add(System.Web.Optimization.Bundle)",
            "TextSpan": {
              "StartCharPosition": 13,
              "EndCharPosition": 50,
              "StartLinePosition": 19,
              "EndLinePosition": 20
            },
            "Package": {
              "PackageId": "System.Web.Optimization",
              "Version": "1.1.0",
              "PackageSourceType": "NUGET"
            }
          },
          "CompatibilityResults": {
            "netcoreapp3.1": {
              "Compatibility": "UNKNOWN",
              "CompatibleVersions": []
            }
          },
          "Recommendations": {
            "RecommendedActions": [
              {
                "CodeEntityDetails": null,
                "RecommendedActionType": "NoRecommendation",
                "Description": null,
                "TextSpan": null,
                "TargetCPU": null,
                "TextChanges": null
              }
            ]
          }
        },
        {
          "CodeEntityDetails": {
            "CodeEntityType": "Namespace",
            "Name": "Include",
            "Namespace": "System.Web.Optimization",
            "Signature": "System.Web.Optimization.Bundle.Include(string, params System.Web.Optimization.IItemTransform[])",
            "OriginalDefinition": "System.Web.Optimization.Bundle.Include(string, params System.Web.Optimization.IItemTransform[])",
            "TextSpan": {
              "StartCharPosition": 25,
              "EndCharPosition": 49,
              "StartLinePosition": 19,
              "EndLinePosition": 20
            },
            "Package": {
              "PackageId": "System.Web.Optimization",
              "Version": "1.1.0",
              "PackageSourceType": "NUGET"
            }
          },
          "CompatibilityResults": {
            "netcoreapp3.1": {
              "Compatibility": "UNKNOWN",
              "CompatibleVersions": []
            }
          },
          "Recommendations": {
            "RecommendedActions": [
              {
                "CodeEntityDetails": null,
                "RecommendedActionType": "NoRecommendation",
                "Description": null,
                "TextSpan": null,
                "TargetCPU": null,
                "TextChanges": null
              }
            ]
          }
        },
        {
          "CodeEntityDetails": {
            "CodeEntityType": "Namespace",
            "Name": "Add",
            "Namespace": "System.Web.Optimization",
            "Signature": "System.Web.Optimization.BundleCollection.Add(System.Web.Optimization.Bundle)",
            "OriginalDefinition": "System.Web.Optimization.BundleCollection.Add(System.Web.Optimization.Bundle)",
            "TextSpan": {
              "StartCharPosition": 13,
              "EndCharPosition": 49,
              "StartLinePosition": 22,
              "EndLinePosition": 23
            },
            "Package": {
              "PackageId": "System.Web.Optimization",
              "Version": "1.1.0",
              "PackageSourceType": "NUGET"
            }
          },
          "CompatibilityResults": {
            "netcoreapp3.1": {
              "Compatibility": "UNKNOWN",
              "CompatibleVersions": []
            }
          },
          "Recommendations": {
            "RecommendedActions": [
              {
                "CodeEntityDetails": null,
                "RecommendedActionType": "NoRecommendation",
                "Description": null,
                "TextSpan": null,
                "TargetCPU": null,
                "TextChanges": null
              }
            ]
          }
        },
        {
          "CodeEntityDetails": {
            "CodeEntityType": "Namespace",
            "Name": "Include",
            "Namespace": "System.Web.Optimization",
